set t_md=
set t_Co=16
set history=500
set wildmenu
set cmdheight=1
set hid
set ignorecase
set smartcase
set lazyredraw
set magic
set showmatch
set mat=2
set noerrorbells
set novisualbell
set t_vb=
set tm=500
syntax on
set encoding=utf8
set ffs=unix,dos,mac

set nobackup
set nowritebackup
set noswapfile

set noexpandtab
set tabstop=3
set shiftwidth=3

set linebreak
set textwidth=96
set autoindent
set smartindent
set wrap

set hlsearch
set incsearch
map <silent> <cr> :noh<cr>

set showtabline=2

let g:currentmode={
			\ 'n'			: 'NORMAL',
			\ 'i'			: 'INSERT',
			\ 'v'			: 'VISUAL',
			\ 'V'			: 'V-LINE',
			\ '\<C-v>'	: 'V-BLCK',
			\ 'r'			: 'REPLCE',
			\ 'Rv'		: 'V-REPL',
			\ 'c'			: 'COMMND'}

set laststatus=2

set noshowmode

set statusline=
set statusline+=%{toupper(g:currentmode[mode()])}

nnoremap <C-J> <C-W><C-J>
nnoremap <C-K> <C-W><C-K>
nnoremap <C-L> <C-W><C-L>
nnoremap <C-H> <C-W><C-H>

set number
set numberwidth=5
highlight LineNr	ctermfg=LightGray
